FROM golang:1.23-alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.11.0

WORKDIR /migrations
COPY internal/db/migrations /migrations

ENTRYPOINT ["/bin/sh", "-c", "goose -dir /migrations postgres \"$DATABASE_URL\" up"]
